### ISSUE TITLE
Feature request:  decoupling the root file definition from the config file

### ISSUE THREAD

**Issue by paulmking** [JeffersonLab/panguin#3]
Allow the root file to be passed as an argument, instead of building it from a prototype and a run number.  Maybe also have the "protorootfile" as an argument.

This would eliminate the need to create many redundant copies of the config files that differed only in the “protorootfile” definition.

Related to this (but not quite the same) would be to abstract the default root file path and file stem definitions from being hardcoded definitions and have some sort of global configuration file that has that for the specific experiment.

**Comment by hansenjo** [comment]
These features are now available in Panguin 2.0. The ROOT file can be given on the command line with the -R/--root-file option. Example:

```
panguin -f myconfig.cfg --root-file=/data/rootfile/myexp_6677.root
```
A ROOT file name specified in this way will override a `rootfile` definition in the configuration file. (A warning will be printed in this case.) This will also automatically extract run number 6677 from the file name. If the ROOT file name doesn't contain an easily parseable run number, the run number can also be set explicitly with the -r/--run option.
 
Global/common definitions can be shared between many configuration files by using the new `include` directive. Example:
```
include common.cfg

newpage 2 2
...
```
Assuming these features hit the mark, I think this issue can be closed.
